//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IHappyHutService")]
public interface IHappyHutService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHappyHutService/SetCustomerRequestInfo", ReplyAction="http://tempuri.org/IHappyHutService/SetCustomerRequestInfoResponse")]
    bool SetCustomerRequestInfo(BussinessObjects.GetQuoteInfo inf, HappyHutService.HappyHutDataBaseEntities Entities);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHappyHutService/SetCustomerRequestInfos", ReplyAction="http://tempuri.org/IHappyHutService/SetCustomerRequestInfosResponse")]
    bool SetCustomerRequestInfos(BussinessObjects.GetQuoteInfo[] infs, HappyHutService.HappyHutDataBaseEntities Entities);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHappyHutService/GetAreasInCity", ReplyAction="http://tempuri.org/IHappyHutService/GetAreasInCityResponse")]
    BussinessObjects.AreaInCityInfo[] GetAreasInCity(int cid, HappyHutService.HappyHutDataBaseEntities Entities);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHappyHutService/GetServicesInArea", ReplyAction="http://tempuri.org/IHappyHutService/GetServicesInAreaResponse")]
    BussinessObjects.ServiceInAreaInfo[] GetServicesInArea(int areaid, HappyHutService.HappyHutDataBaseEntities Entities);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHappyHutService/GetServiceInArea", ReplyAction="http://tempuri.org/IHappyHutService/GetServiceInAreaResponse")]
    BussinessObjects.ServiceInAreaInfo GetServiceInArea(int nAreaId, int nServiceId, HappyHutService.HappyHutDataBaseEntities Entities);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHappyHutService/GetCityList", ReplyAction="http://tempuri.org/IHappyHutService/GetCityListResponse")]
    BussinessObjects.CityInfo[] GetCityList(HappyHutService.HappyHutDataBaseEntities Entities);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHappyHutService/GetRequestsToSendEmail", ReplyAction="http://tempuri.org/IHappyHutService/GetRequestsToSendEmailResponse")]
    BussinessObjects.GetQuoteInfo[] GetRequestsToSendEmail(HappyHutService.HappyHutDataBaseEntities Entities);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHappyHutService/SetHappyHutUserInfo", ReplyAction="http://tempuri.org/IHappyHutService/SetHappyHutUserInfoResponse")]
    bool SetHappyHutUserInfo(BussinessObjects.HappyHutUserInfo inf, HappyHutService.HappyHutDataBaseEntities Entities);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHappyHutService/SetHappyHutUsersInfos", ReplyAction="http://tempuri.org/IHappyHutService/SetHappyHutUsersInfosResponse")]
    bool SetHappyHutUsersInfos(BussinessObjects.HappyHutUserInfo[] infs, HappyHutService.HappyHutDataBaseEntities Entities);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHappyHutService/GetServices", ReplyAction="http://tempuri.org/IHappyHutService/GetServicesResponse")]
    BussinessObjects.ServiceInfo[] GetServices(HappyHutService.HappyHutDataBaseEntities Entities);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IHappyHutServiceChannel : IHappyHutService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HappyHutServiceClient : System.ServiceModel.ClientBase<IHappyHutService>, IHappyHutService
{
    
    public HappyHutServiceClient()
    {
    }
    
    public HappyHutServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HappyHutServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HappyHutServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HappyHutServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool SetCustomerRequestInfo(BussinessObjects.GetQuoteInfo inf, HappyHutService.HappyHutDataBaseEntities Entities)
    {
        return base.Channel.SetCustomerRequestInfo(inf, Entities);
    }
    
    public bool SetCustomerRequestInfos(BussinessObjects.GetQuoteInfo[] infs, HappyHutService.HappyHutDataBaseEntities Entities)
    {
        return base.Channel.SetCustomerRequestInfos(infs, Entities);
    }
    
    public BussinessObjects.AreaInCityInfo[] GetAreasInCity(int cid, HappyHutService.HappyHutDataBaseEntities Entities)
    {
        return base.Channel.GetAreasInCity(cid, Entities);
    }
    
    public BussinessObjects.ServiceInAreaInfo[] GetServicesInArea(int areaid, HappyHutService.HappyHutDataBaseEntities Entities)
    {
        return base.Channel.GetServicesInArea(areaid, Entities);
    }
    
    public BussinessObjects.ServiceInAreaInfo GetServiceInArea(int nAreaId, int nServiceId, HappyHutService.HappyHutDataBaseEntities Entities)
    {
        return base.Channel.GetServiceInArea(nAreaId, nServiceId, Entities);
    }
    
    public BussinessObjects.CityInfo[] GetCityList(HappyHutService.HappyHutDataBaseEntities Entities)
    {
        return base.Channel.GetCityList(Entities);
    }
    
    public BussinessObjects.GetQuoteInfo[] GetRequestsToSendEmail(HappyHutService.HappyHutDataBaseEntities Entities)
    {
        return base.Channel.GetRequestsToSendEmail(Entities);
    }
    
    public bool SetHappyHutUserInfo(BussinessObjects.HappyHutUserInfo inf, HappyHutService.HappyHutDataBaseEntities Entities)
    {
        return base.Channel.SetHappyHutUserInfo(inf, Entities);
    }
    
    public bool SetHappyHutUsersInfos(BussinessObjects.HappyHutUserInfo[] infs, HappyHutService.HappyHutDataBaseEntities Entities)
    {
        return base.Channel.SetHappyHutUsersInfos(infs, Entities);
    }
    
    public BussinessObjects.ServiceInfo[] GetServices(HappyHutService.HappyHutDataBaseEntities Entities)
    {
        return base.Channel.GetServices(Entities);
    }
}
namespace BussinessObjects
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetQuoteInfo", Namespace="http://schemas.datacontract.org/2004/07/BussinessObjects")]
    public partial class GetQuoteInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AdditionalInfoField;
        
        private int CityIdField;
        
        private System.DateTime CreateDtField;
        
        private string EmailField;
        
        private System.DateTime EmailSentDtField;
        
        private string FirstNameField;
        
        private System.Guid IdField;
        
        private bool IsEmailSentField;
        
        private string LastNameField;
        
        private System.DateTime LastUpdateDtField;
        
        private string MobileNumberField;
        
        private bool NeedToCreateUserField;
        
        private System.DateTime PreferredDateField;
        
        private System.TimeSpan PreferredTimeField;
        
        private int ServiceIdField;
        
        private string ServiceNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalInfo
        {
            get
            {
                return this.AdditionalInfoField;
            }
            set
            {
                this.AdditionalInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityId
        {
            get
            {
                return this.CityIdField;
            }
            set
            {
                this.CityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDt
        {
            get
            {
                return this.CreateDtField;
            }
            set
            {
                this.CreateDtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EmailSentDt
        {
            get
            {
                return this.EmailSentDtField;
            }
            set
            {
                this.EmailSentDtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEmailSent
        {
            get
            {
                return this.IsEmailSentField;
            }
            set
            {
                this.IsEmailSentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdateDt
        {
            get
            {
                return this.LastUpdateDtField;
            }
            set
            {
                this.LastUpdateDtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NeedToCreateUser
        {
            get
            {
                return this.NeedToCreateUserField;
            }
            set
            {
                this.NeedToCreateUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PreferredDate
        {
            get
            {
                return this.PreferredDateField;
            }
            set
            {
                this.PreferredDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan PreferredTime
        {
            get
            {
                return this.PreferredTimeField;
            }
            set
            {
                this.PreferredTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServiceId
        {
            get
            {
                return this.ServiceIdField;
            }
            set
            {
                this.ServiceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceName
        {
            get
            {
                return this.ServiceNameField;
            }
            set
            {
                this.ServiceNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AreaInCityInfo", Namespace="http://schemas.datacontract.org/2004/07/BussinessObjects")]
    public partial class AreaInCityInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CityIDField;
        
        private int IDField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityID
        {
            get
            {
                return this.CityIDField;
            }
            set
            {
                this.CityIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceInAreaInfo", Namespace="http://schemas.datacontract.org/2004/07/BussinessObjects")]
    public partial class ServiceInAreaInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AreaIDField;
        
        private bool IsActiveField;
        
        private int ServiceIDField;
        
        private int ServiceInAreaIdField;
        
        private string ServiceNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AreaID
        {
            get
            {
                return this.AreaIDField;
            }
            set
            {
                this.AreaIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServiceID
        {
            get
            {
                return this.ServiceIDField;
            }
            set
            {
                this.ServiceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServiceInAreaId
        {
            get
            {
                return this.ServiceInAreaIdField;
            }
            set
            {
                this.ServiceInAreaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceName
        {
            get
            {
                return this.ServiceNameField;
            }
            set
            {
                this.ServiceNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CityInfo", Namespace="http://schemas.datacontract.org/2004/07/BussinessObjects")]
    public partial class CityInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HappyHutUserInfo", Namespace="http://schemas.datacontract.org/2004/07/BussinessObjects")]
    public partial class HappyHutUserInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressLine1Field;
        
        private string AddressLine2Field;
        
        private int CityIdField;
        
        private string CityNameField;
        
        private string CreateDtField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private bool IsFirstLoginField;
        
        private string LastNameField;
        
        private string LastUpdateDtField;
        
        private string MobileNumberField;
        
        private int StateIdField;
        
        private string StateNameField;
        
        private string UserIdField;
        
        private string UsernameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1
        {
            get
            {
                return this.AddressLine1Field;
            }
            set
            {
                this.AddressLine1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2
        {
            get
            {
                return this.AddressLine2Field;
            }
            set
            {
                this.AddressLine2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityId
        {
            get
            {
                return this.CityIdField;
            }
            set
            {
                this.CityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityName
        {
            get
            {
                return this.CityNameField;
            }
            set
            {
                this.CityNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateDt
        {
            get
            {
                return this.CreateDtField;
            }
            set
            {
                this.CreateDtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFirstLogin
        {
            get
            {
                return this.IsFirstLoginField;
            }
            set
            {
                this.IsFirstLoginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUpdateDt
        {
            get
            {
                return this.LastUpdateDtField;
            }
            set
            {
                this.LastUpdateDtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateId
        {
            get
            {
                return this.StateIdField;
            }
            set
            {
                this.StateIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateName
        {
            get
            {
                return this.StateNameField;
            }
            set
            {
                this.StateNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceInfo", Namespace="http://schemas.datacontract.org/2004/07/BussinessObjects")]
    public partial class ServiceInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
}
namespace System.Data.Entity
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DbContext", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Entity")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HappyHutService.HappyHutDataBaseEntities))]
    public partial class DbContext : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
}
namespace HappyHutService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HappyHutDataBaseEntities", Namespace="http://schemas.datacontract.org/2004/07/HappyHutService")]
    public partial class HappyHutDataBaseEntities : System.Data.Entity.DbContext
    {
        
        private HappyHutService.AreasInCity[] AreasInCitiesField;
        
        private HappyHutService.AspNetRole[] AspNetRolesField;
        
        private HappyHutService.AspNetUserClaim[] AspNetUserClaimsField;
        
        private HappyHutService.AspNetUserLogin[] AspNetUserLoginsField;
        
        private HappyHutService.AspNetUser[] AspNetUsersField;
        
        private HappyHutService.C__MigrationHistory[] C__MigrationHistoryField;
        
        private HappyHutService.City[] CitiesField;
        
        private HappyHutService.GetQuoteRequest[] GetQuoteRequestsField;
        
        private HappyHutService.HappyHutUser[] HappyHutUsersField;
        
        private HappyHutService.Service[] ServicesField;
        
        private HappyHutService.ServicesInArea[] ServicesInAreasField;
        
        private HappyHutService.State[] StatesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.AreasInCity[] AreasInCities
        {
            get
            {
                return this.AreasInCitiesField;
            }
            set
            {
                this.AreasInCitiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.AspNetRole[] AspNetRoles
        {
            get
            {
                return this.AspNetRolesField;
            }
            set
            {
                this.AspNetRolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.AspNetUserClaim[] AspNetUserClaims
        {
            get
            {
                return this.AspNetUserClaimsField;
            }
            set
            {
                this.AspNetUserClaimsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.AspNetUserLogin[] AspNetUserLogins
        {
            get
            {
                return this.AspNetUserLoginsField;
            }
            set
            {
                this.AspNetUserLoginsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.AspNetUser[] AspNetUsers
        {
            get
            {
                return this.AspNetUsersField;
            }
            set
            {
                this.AspNetUsersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.C__MigrationHistory[] C__MigrationHistory
        {
            get
            {
                return this.C__MigrationHistoryField;
            }
            set
            {
                this.C__MigrationHistoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.City[] Cities
        {
            get
            {
                return this.CitiesField;
            }
            set
            {
                this.CitiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.GetQuoteRequest[] GetQuoteRequests
        {
            get
            {
                return this.GetQuoteRequestsField;
            }
            set
            {
                this.GetQuoteRequestsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.HappyHutUser[] HappyHutUsers
        {
            get
            {
                return this.HappyHutUsersField;
            }
            set
            {
                this.HappyHutUsersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.Service[] Services
        {
            get
            {
                return this.ServicesField;
            }
            set
            {
                this.ServicesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.ServicesInArea[] ServicesInAreas
        {
            get
            {
                return this.ServicesInAreasField;
            }
            set
            {
                this.ServicesInAreasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.State[] States
        {
            get
            {
                return this.StatesField;
            }
            set
            {
                this.StatesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AreasInCity", Namespace="http://schemas.datacontract.org/2004/07/HappyHutService")]
    public partial class AreasInCity : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private HappyHutService.City CityField;
        
        private int CityIDField;
        
        private int IDField;
        
        private string NameField;
        
        private HappyHutService.ServicesInArea[] ServicesInAreasField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.City City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityID
        {
            get
            {
                return this.CityIDField;
            }
            set
            {
                this.CityIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.ServicesInArea[] ServicesInAreas
        {
            get
            {
                return this.ServicesInAreasField;
            }
            set
            {
                this.ServicesInAreasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AspNetRole", Namespace="http://schemas.datacontract.org/2004/07/HappyHutService")]
    public partial class AspNetRole : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private HappyHutService.AspNetUser[] AspNetUsersField;
        
        private string IdField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.AspNetUser[] AspNetUsers
        {
            get
            {
                return this.AspNetUsersField;
            }
            set
            {
                this.AspNetUsersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AspNetUserClaim", Namespace="http://schemas.datacontract.org/2004/07/HappyHutService")]
    public partial class AspNetUserClaim : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private HappyHutService.AspNetUser AspNetUserField;
        
        private string ClaimTypeField;
        
        private string ClaimValueField;
        
        private int IdField;
        
        private string UserIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.AspNetUser AspNetUser
        {
            get
            {
                return this.AspNetUserField;
            }
            set
            {
                this.AspNetUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimType
        {
            get
            {
                return this.ClaimTypeField;
            }
            set
            {
                this.ClaimTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimValue
        {
            get
            {
                return this.ClaimValueField;
            }
            set
            {
                this.ClaimValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AspNetUserLogin", Namespace="http://schemas.datacontract.org/2004/07/HappyHutService")]
    public partial class AspNetUserLogin : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private HappyHutService.AspNetUser AspNetUserField;
        
        private string LoginProviderField;
        
        private string ProviderKeyField;
        
        private string UserIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.AspNetUser AspNetUser
        {
            get
            {
                return this.AspNetUserField;
            }
            set
            {
                this.AspNetUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginProvider
        {
            get
            {
                return this.LoginProviderField;
            }
            set
            {
                this.LoginProviderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProviderKey
        {
            get
            {
                return this.ProviderKeyField;
            }
            set
            {
                this.ProviderKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AspNetUser", Namespace="http://schemas.datacontract.org/2004/07/HappyHutService")]
    public partial class AspNetUser : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AccessFailedCountField;
        
        private HappyHutService.AspNetRole[] AspNetRolesField;
        
        private HappyHutService.AspNetUserClaim[] AspNetUserClaimsField;
        
        private HappyHutService.AspNetUserLogin[] AspNetUserLoginsField;
        
        private string EmailField;
        
        private bool EmailConfirmedField;
        
        private HappyHutService.HappyHutUser HappyHutUserField;
        
        private string IdField;
        
        private bool LockoutEnabledField;
        
        private System.Nullable<System.DateTime> LockoutEndDateUtcField;
        
        private string PasswordHashField;
        
        private string PhoneNumberField;
        
        private bool PhoneNumberConfirmedField;
        
        private string SecurityStampField;
        
        private bool TwoFactorEnabledField;
        
        private string UserNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccessFailedCount
        {
            get
            {
                return this.AccessFailedCountField;
            }
            set
            {
                this.AccessFailedCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.AspNetRole[] AspNetRoles
        {
            get
            {
                return this.AspNetRolesField;
            }
            set
            {
                this.AspNetRolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.AspNetUserClaim[] AspNetUserClaims
        {
            get
            {
                return this.AspNetUserClaimsField;
            }
            set
            {
                this.AspNetUserClaimsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.AspNetUserLogin[] AspNetUserLogins
        {
            get
            {
                return this.AspNetUserLoginsField;
            }
            set
            {
                this.AspNetUserLoginsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EmailConfirmed
        {
            get
            {
                return this.EmailConfirmedField;
            }
            set
            {
                this.EmailConfirmedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.HappyHutUser HappyHutUser
        {
            get
            {
                return this.HappyHutUserField;
            }
            set
            {
                this.HappyHutUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LockoutEnabled
        {
            get
            {
                return this.LockoutEnabledField;
            }
            set
            {
                this.LockoutEnabledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LockoutEndDateUtc
        {
            get
            {
                return this.LockoutEndDateUtcField;
            }
            set
            {
                this.LockoutEndDateUtcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash
        {
            get
            {
                return this.PasswordHashField;
            }
            set
            {
                this.PasswordHashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PhoneNumberConfirmed
        {
            get
            {
                return this.PhoneNumberConfirmedField;
            }
            set
            {
                this.PhoneNumberConfirmedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityStamp
        {
            get
            {
                return this.SecurityStampField;
            }
            set
            {
                this.SecurityStampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TwoFactorEnabled
        {
            get
            {
                return this.TwoFactorEnabledField;
            }
            set
            {
                this.TwoFactorEnabledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C__MigrationHistory", Namespace="http://schemas.datacontract.org/2004/07/HappyHutService")]
    public partial class C__MigrationHistory : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ContextKeyField;
        
        private string MigrationIdField;
        
        private byte[] ModelField;
        
        private string ProductVersionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContextKey
        {
            get
            {
                return this.ContextKeyField;
            }
            set
            {
                this.ContextKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MigrationId
        {
            get
            {
                return this.MigrationIdField;
            }
            set
            {
                this.MigrationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Model
        {
            get
            {
                return this.ModelField;
            }
            set
            {
                this.ModelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductVersion
        {
            get
            {
                return this.ProductVersionField;
            }
            set
            {
                this.ProductVersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://schemas.datacontract.org/2004/07/HappyHutService")]
    public partial class City : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private HappyHutService.AreasInCity[] AreasInCitiesField;
        
        private int IDField;
        
        private string NameField;
        
        private HappyHutService.State StateField;
        
        private int StateIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.AreasInCity[] AreasInCities
        {
            get
            {
                return this.AreasInCitiesField;
            }
            set
            {
                this.AreasInCitiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.State State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateId
        {
            get
            {
                return this.StateIdField;
            }
            set
            {
                this.StateIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetQuoteRequest", Namespace="http://schemas.datacontract.org/2004/07/HappyHutService")]
    public partial class GetQuoteRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AdditionalInfoField;
        
        private System.DateTime CreateDtField;
        
        private string EmailField;
        
        private System.Nullable<System.DateTime> EmailSentDtField;
        
        private string FirstNameField;
        
        private System.Guid IdField;
        
        private bool IsEmailSentField;
        
        private string LastNameField;
        
        private System.DateTime LastUpdateDtField;
        
        private string MobileNumberField;
        
        private System.DateTime PreferredDateField;
        
        private System.TimeSpan PreferredTimeField;
        
        private int ServiceIdField;
        
        private HappyHutService.ServicesInArea ServicesInAreaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalInfo
        {
            get
            {
                return this.AdditionalInfoField;
            }
            set
            {
                this.AdditionalInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDt
        {
            get
            {
                return this.CreateDtField;
            }
            set
            {
                this.CreateDtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EmailSentDt
        {
            get
            {
                return this.EmailSentDtField;
            }
            set
            {
                this.EmailSentDtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEmailSent
        {
            get
            {
                return this.IsEmailSentField;
            }
            set
            {
                this.IsEmailSentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdateDt
        {
            get
            {
                return this.LastUpdateDtField;
            }
            set
            {
                this.LastUpdateDtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PreferredDate
        {
            get
            {
                return this.PreferredDateField;
            }
            set
            {
                this.PreferredDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan PreferredTime
        {
            get
            {
                return this.PreferredTimeField;
            }
            set
            {
                this.PreferredTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServiceId
        {
            get
            {
                return this.ServiceIdField;
            }
            set
            {
                this.ServiceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.ServicesInArea ServicesInArea
        {
            get
            {
                return this.ServicesInAreaField;
            }
            set
            {
                this.ServicesInAreaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HappyHutUser", Namespace="http://schemas.datacontract.org/2004/07/HappyHutService")]
    public partial class HappyHutUser : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressLine1Field;
        
        private string AddressLine2Field;
        
        private HappyHutService.AspNetUser AspNetUserField;
        
        private int CityIdField;
        
        private System.DateTime CreateDtField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private bool IsFirstLoginField;
        
        private string LastNameField;
        
        private System.DateTime LastUpdateDtField;
        
        private string MobileNumberField;
        
        private int StateIdField;
        
        private string UserIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1
        {
            get
            {
                return this.AddressLine1Field;
            }
            set
            {
                this.AddressLine1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2
        {
            get
            {
                return this.AddressLine2Field;
            }
            set
            {
                this.AddressLine2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.AspNetUser AspNetUser
        {
            get
            {
                return this.AspNetUserField;
            }
            set
            {
                this.AspNetUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityId
        {
            get
            {
                return this.CityIdField;
            }
            set
            {
                this.CityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDt
        {
            get
            {
                return this.CreateDtField;
            }
            set
            {
                this.CreateDtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFirstLogin
        {
            get
            {
                return this.IsFirstLoginField;
            }
            set
            {
                this.IsFirstLoginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdateDt
        {
            get
            {
                return this.LastUpdateDtField;
            }
            set
            {
                this.LastUpdateDtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateId
        {
            get
            {
                return this.StateIdField;
            }
            set
            {
                this.StateIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Service", Namespace="http://schemas.datacontract.org/2004/07/HappyHutService")]
    public partial class Service : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private string NameField;
        
        private HappyHutService.ServicesInArea[] ServicesInAreasField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHutService.ServicesInArea[] ServicesInAreas
        {
            get
            {
                return this.ServicesInAreasField;
            }
            set
            {
                this.ServicesInAreasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServicesInArea", Namespac