//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyHutMiddleTier
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.AreasInCities = new HashSet<AreasInCity>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int StateId { get; set; }
    
        public virtual ICollection<AreasInCity> AreasInCities { get; set; }
        public virtual State State { get; set; }
    }
}
