//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyHutMiddleTier
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesInArea
    {
        public ServicesInArea()
        {
            this.GetQuoteRequests = new HashSet<GetQuoteRequest>();
        }
    
        public int Id { get; set; }
        public int ServiceID { get; set; }
        public int AreaID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AreasInCity AreasInCity { get; set; }
        public virtual ICollection<GetQuoteRequest> GetQuoteRequests { get; set; }
        public virtual Service Service { get; set; }
    }
}
